[workspace]

members = [
    "01-hello-world",
    "02-variables",
    "03-strings",
    "04-arrays",
    "05-functions",
    "06-ownership",
    "07-control-flow",
    "08-errors",
    "09-modules",
    "10-types",
    "11-traits",
    "12-iterators",
]
