[workspace]

members = [
    "01-hello-world",
    "02-variables",
    "03-strings",
    "04-arrays",
    "05-functions",
    "06-ownership",
    "07-control-flow",
    "08-modules",
    "09-types",
    "10-traits",
    "11-iterators",
]
